FROM python:3.10-slim

WORKDIR C:\Users\aksme\Desktop\Insuarance_Fraud\insurance-fraud-detection\Sabarish_Rajan\Backend

COPY requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ['uvicorn', 'my_API_2', '--host', '0.0.0.0', '--port', '8000']